use pyo3::prelude::*;
pub mod error;
pub mod package;
pub mod package_schema;
pub mod schema;
pub mod xml;
pub mod text;
pub mod definitions;
pub mod tables;
pub mod revisions;
pub mod compare;
pub mod comments;
pub mod links;
pub mod importing;

#[pymodule]
fn _core(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<xml::Xml>()?;
    m.add_class::<package::Package>()?;
    m.add_class::<package::Part>()?;
    m.add_class::<text::Story>()?;
    m.add_class::<text::Range>()?;
    m.add_class::<definitions::Style>()?;
    m.add_class::<definitions::Level>()?;
    m.add_class::<definitions::NumberingInstance>()?;
    m.add_class::<tables::Table>()?;
    m.add_class::<comments::Comments>()?;
    m.add_class::<comments::Comment>()?;
    m.add_class::<links::Bookmarks>()?;
    m.add_class::<links::Bookmark>()?;
    m.add_class::<links::Hyperlinks>()?;
    m.add_class::<links::Hyperlink>()?;
    m.add_function(wrap_pyfunction!(definitions::style_items, m)?)?;
    m.add_function(wrap_pyfunction!(definitions::style_get, m)?)?;
    m.add_function(wrap_pyfunction!(definitions::style_find, m)?)?;
    m.add_function(wrap_pyfunction!(definitions::style_add, m)?)?;
    m.add_function(wrap_pyfunction!(definitions::numbering_items, m)?)?;
    m.add_function(wrap_pyfunction!(definitions::numbering_get, m)?)?;
    m.add_function(wrap_pyfunction!(definitions::numbering_add, m)?)?;
    m.add_function(wrap_pyfunction!(text::split, m)?)?;
    m.add_function(wrap_pyfunction!(text::join_pair, m)?)?;
    m.add_function(wrap_pyfunction!(schema::namespace_bindings, m)?)?;
    m.add_function(wrap_pyfunction!(schema::facade_enums, m)?)?;
    m.add_function(wrap_pyfunction!(schema::facade_types, m)?)?;
    m.add_function(wrap_pyfunction!(schema::analyze, m)?)?;
    m.add_function(wrap_pyfunction!(schema::element_type, m)?)?;
    m.add_function(wrap_pyfunction!(schema::check_element_type, m)?)?;
    m.add_function(wrap_pyfunction!(schema::elements_of_type, m)?)?;
    m.add_function(wrap_pyfunction!(schema::child_position, m)?)?;
    m.add_function(wrap_pyfunction!(schema::typed_attribute, m)?)?;
    m.add_function(wrap_pyfunction!(schema::set_typed_attribute, m)?)?;
    m.add_function(wrap_pyfunction!(package_schema::declared_part, m)?)?;
    m.add_function(wrap_pyfunction!(package_schema::package_stories, m)?)?;
    m.add_function(wrap_pyfunction!(package_schema::validate_package, m)?)?;
    m.add_function(wrap_pyfunction!(revisions::revision_ids, m)?)?;
    m.add_function(wrap_pyfunction!(revisions::revision_info, m)?)?;
    m.add_function(wrap_pyfunction!(revisions::revision_properties, m)?)?;
    m.add_function(wrap_pyfunction!(revisions::revision_apply, m)?)?;
    m.add_function(wrap_pyfunction!(revisions::revisions_apply, m)?)?;
    m.add_function(wrap_pyfunction!(revisions::revisions_replace, m)?)?;
    m.add_function(wrap_pyfunction!(revisions::revisions_format, m)?)?;
    m.add_function(wrap_pyfunction!(compare::compare, m)?)?;
    m.add_function(wrap_pyfunction!(importing::import_content, m)?)?;
    m.add("__version__", env!("CARGO_PKG_VERSION"))?;
    Ok(())
}
